spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
server:
  port: 8081
jwt:
  rsa-private-key: classpath:certs/privateKey.pem
  rsa-public-key: classpath:certs/publicKey.pem
logging:
  level:
    org.springframework.security: trace
