name: hw-pipeline

on:
  pull_request:
    branches:
      - 'hw**'

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
        run: |
          mvn verify --no-transfer-progress