name: homework-pipeline

on:
  pull_request:
    branches:
      - 'hw**'

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: maven-action
        run: |
          mvn verify --no-transfer-progress